name: playlist_music
description: "A simple music playlist viewer."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  dio: ^5.9.0
  pull_to_refresh_flutter3: ^2.0.2
  loading_animation_widget: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_app.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon/logo_app.png"
    background_color: "#000000"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

  fonts:
    - family: Mitr
      fonts:
        - asset: assets/fonts/Mitr-Regular.ttf
        - asset: assets/fonts/Mitr-Bold.ttf
        - asset: assets/fonts/Mitr-Light.ttf
        - asset: assets/fonts/Mitr-Medium.ttf
